version: "3.8"
services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PetCare
      - POSTGRES_DB=PetCare_bd
    ports:
      - '5432:5432'
  app:
    container_name: petcare_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/PetCare_bd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=PetCare
      - spring.jpa.generate-ddl=true
    depends_on:
      - psql-db